DROP DATABASE IF EXISTS banco;
CREATE DATABASE banco;
USE banco;

DROP TABLE IF EXISTS cuentas;

CREATE TABLE cuentas (
    id INT PRIMARY KEY AUTO_INCREMENT UNIQUE,
    saldo DECIMAL(10,2) NOT NULL
);

INSERT INTO cuentas (saldo) VALUES
(1000.00),
(2000.00),
(3000.00);